name: DEPLOY
on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
        
    steps:

      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version}}
      - name: Set up key
        run: set -eu
      - name: Choose directory
        run: mkdir "$HOME/.ssh"
      - name: Key
        run: echo "${{ secrets.BUILD }}" > "$HOME/.ssh/BUILD"
      - name: Finish set key
        run: chmod 600 "$HOME/.ssh/BUILD"
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build
     # - name: Deploy
     #   run: cd build && rsync -e "ssh -i $HOME/.ssh/BUILD -o StrictHostKeyChecking=no" --archive --compress --delete .ChipRose@Cat-energy:/var/www/Cat-energy/html/
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          branch: master # The branch the action should deploy to.
          folder: / # The folder the action should deploy.
